### ISSUE TITLE
MySqlDataAdapter.Update within MySql.Data Outperforms MySqlConnector Version By A Very Large Margin

### ISSUE THREAD

**Issue by mrogunlana** [mrogunlana/Panama.Core#15]
`Panama.Core.MySql.Dapper` has added a reference to `MySql.Data` only for `InsertBatch` support as it seems to out perform `MySqlConnector` on its `MySqlDataAdapter.Update()` function by a high order of magnitude; for example, batch inserting 100K rows of data using `MySqlConnector` takes on average of 20 minutes; where as `MySql.Data` inserts the same recordset in under a minute. 

This issue was mentioned in the `MySqlConnector` repo here https://github.com/mysql-net/MySqlConnector/issues/673 but it appears that the issue still exists. In the latest version `MySqlConnector` v2.1.4. Benchmarks should be re-evaluated to determine if Panama.Core should just be updated to the latest version of .NET Core to resolve this issue or if there is some sort of user error that is causing the issue. 

I've temporarily released a version of `Panama.Core.Mysql.Dapper` v2.0.13 (https://www.nuget.org/packages/Panama.Core.MySql.Dapper/2.0.13) with `MySql.Data` reference for now to resolve this issue; it would be nice to understand why this is happening and possibly get a solution with just `MySqlConnector`. 

Here the synchronous `InsertBatch` as an example reference: https://github.com/mrogunlana/Panama.Core/blob/master/Panama.MySql.Dapper/MySqlQuery.cs#L568

**Comment by bgrainger** [comment]
@mrogunlana Are you able to provide either of the following as sample apps that demonstrate the problem?

1. A plain ADO.NET example without Panama (perhaps similar to https://github.com/mysql-net/MySqlConnector/issues/1124#issuecomment-1024970871)
2. A simple, self-contained Panama example. I read the README but wasn't able to figure out the minimum amount of code to bootstrap Panama and insert a batch.

**Comment by bgrainger** [comment]
I managed to get a simple Panama MySQL app running. The time to insert 10,000 users was:

* 2.0.12 - 12.9 seconds
* 2.0.13 - 19.6 seconds

Thus, in my testing, MySql.Data was much slower. I'll need a concrete, reproducible example to examine further.

**Comment by mrogunlana** [comment]
@bgrainger thanks for chiming in on this; I whipped up a few unit tests with a dataset of 100K models that get hydrated within a command from a csv. The models are then persisted into the database in a separate query command. I created 3 unit test that covers the scenarios you requested above.

If you'd like to run the unit test locally, you could:
1. Clone the repo
2. Load the MySql database in a docker container using, cd .\Panama.Core\Panama.Database.MySql
3. Then run: docker-compose -f docker-compose.yml up
4. The test database creds are located here: https://github.com/mrogunlana/Panama.Core/blob/master/Panama.Database.MySql/.env
5. Once the database is online, open the test project in the IDE of your choice
6. Run the following tests in this class: https://github.com/mrogunlana/Panama.Core/blob/master/Panama.Core.Tests/BatchPerformanceTests.cs

Here is a snapshot of the test results:

![image](https://user-images.githubusercontent.com/11683585/151698771-1f6a9f36-da85-4fed-a45b-18bfbae90394.png)

`MySqlConnector` seems to run about a minute behind `MySql.Data` and `Panama.Core.MySql.Dapper` (which uses `MySql.Data` for now)

If you need any help, just let me know and I'll get back to you ASAP!

Thank you so much for quick response on this.

**Comment by bgrainger** [comment]
@mrogunlana Thanks for the instructions to get it running!

I cloned it locally and the MySqlConnector tests ran in 8.8 minutes.

I updated the local build to use the new code in https://github.com/mysql-net/MySqlConnector/issues/1124#issuecomment-1025080977 and the tests passed in 10.5 seconds (50× faster).

You should be able to switch back to MySqlConnector once I publish a new package version.

**Comment by mrogunlana** [comment]
@bgrainger great! let me know when the package is ready and I'll verify it in both the Panama.Core unit tests and in my production scenarios

**Comment by bgrainger** [comment]
This improvement is available in [MySqlConnector 2.1.5](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.5).

**Comment by mrogunlana** [comment]
@bgrainger confirmed in `Panama.Core` unit test:

![image](https://user-images.githubusercontent.com/11683585/151723607-71594c5e-bcb8-412c-8131-eea977c14e5a.png)

I'll update the `Panama.Core.MySql.Dapper` library and run some production data through and let you know

**Comment by mrogunlana** [comment]
Also confirmed the MySqlConnector 2.1.5 update with production data: 

![image](https://user-images.githubusercontent.com/11683585/151725055-2fc6722a-9b15-4eff-9db8-abaf2d1c4949.png)

CC: @bgrainger
