### ISSUE TITLE
Add Trace Logging Entries in Panama.Core.MySql.Dapper.MySqlQuery Functions

### ISSUE THREAD

**Issue by mrogunlana** [mrogunlana/Panama.Core#4]
would be a nice to have to implement ILog.Trace on all functions in this class to enable consumer to view CRUD ops via configuration (e.g. NLog, etc)

**Comment by oneEyedSunday** [comment]
I think we already have this in place, albeit not in all commands. See:
- https://github.com/mrogunlana/Panama.Core/blob/master/Panama.MySql.Dapper/MySqlQuery.cs#L86
- https://github.com/mrogunlana/Panama.Core/blob/master/Panama.MySql.Dapper/MySqlQueryAsync.cs#L238
