### ISSUE TITLE
Handle Transactions - Command Level Rollbacks

### ISSUE THREAD

**Issue by mrogunlana** [mrogunlana/Panama.Core#8]
for tracking purposes. 

to handle the case of invalid database scripts or runtime database exceptions which should rollback database state.

**Comment by oneEyedSunday** [comment]
From [Gitlab PR review](https://gitlab.com/mrogunlana/iak-msi-ec2/-/merge_requests/291#note_578808720)
```
An easy way out would probably be to wrap all SQL in transactions that don't auto commit.
Then rollback on error, commit otherwise.
Hard way will be to find out the opposing SQL, (may be impossible with things like IDs)
```

**Comment by mrogunlana** [comment]
Yes, adding transactions to each `MySqlQueryAsync` would be the easy route. I think the more involved solution would be implementing `TransactionScope` which is the ado.net way to marshal transactions; I could be a viable approach since we're essentially in a distributing units of work as commands; but it can be expensive memory wise. if it works how I think it does, I could add some syntax sugar to the fluent api to create the transaction scope and pass along the scope. 

Edit: looks like `TransactionScope` is not supported, some interesting tidbits to consider for ideas, let me know what you think?: 

1. https://stackoverflow.com/questions/59403689/how-transactionscope-work-with-multi-threads
2. https://stackoverflow.com/questions/56328832/transactionscope-throwing-exception-this-platform-does-not-support-distributed-t/56332021#56332021
3. https://github.com/dotnet/runtime/issues/715

**Comment by mrogunlana** [comment]
Currently looking into the SAGA pattern for inspiration: 
https://microservices.io/patterns/data/saga.html

**Comment by mrogunlana** [comment]
Changed the name since I think the original concept is actually more geared towards the lifecycle of a command; right now when a command executes and fails, the rollback actions run on a handler instead of on a command level; to provide more granularity and also to allow consumer systems the ability to implement compensating actions on a failure event would solve the problem.

**Comment by mrogunlana** [comment]
Here's what I'm visualizing a handler would look like: 

```
var result= await new Handler(ServiceLocator.Current)
	.Add(context.CancellationToken)
	.Add(new KeyValuePair("EntityId", Guid.Parse(request.EntityId)))
	.Transaction()
	.Validate<EntityIdNotNullOrEmpty>()
	.Command<GetDataByEntityId>()
	.Command<InsertUsers>()
	.Command<UpdateRequest>()
	.Rollback<InsertUsers>()
	.InvokeAsync();
```

take note of `.Rollback<InsertUsers>()` where its `IRollback` implementation would look like so: 

```
public class InsertUsers : IRollback<InsertUsers>
{
	private readonly IService service;

	public InsertUsers(IService service)
	{
		this.service = service;
	}

	public async Task Execute(Subject subject)
	{
		//reverse InsertUsers command specific action
		//using same data context
    }
}
```

outside the obvious namespace collision of the class name `InsertUsers`; the primary feature would be `IRollback<InsertUsers>` where a consumer could potentially have multiple rollback actions `IRollback<InsertUsers>` if desired. I guess the main point here would be the fact that `ICommand` remains SOLID and we add separate implementation of `IRollback` on a command level. In theory, the handler would need to be updated to support this new type, specifically the `Invoke` methods. We could handle exceptions on a command level where we'd execute the rollback commands related to a specific command...

**Comment by mrogunlana** [comment]
not sure if this is still needed?

**Comment by oneEyedSunday** [comment]
I think its too use case specific and may be hard to model

**Comment by mrogunlana** [comment]
This is worth some continued investigation:
Keyword search:  "how does dapper handle transactions"

Some interesting results: https://stackoverflow.com/questions/10363933/how-to-use-transactions-with-dapper-net

**Comment by mrogunlana** [comment]
What I'd be looking for is a way to pass the scope of a transaction to commands via `Subject`  and to the `IMySqlQuery` implementation which should execute independent queries against this scope

**Comment by mrogunlana** [comment]
an example of how a handler would look:

```
var result= await new Handler(ServiceLocator.Current)
	.Add(context.CancellationToken)
	.Add(new KeyValuePair("EntityId", Guid.Parse(request.EntityId)))
	.Transaction()
	.Validate<EntityIdNotNullOrEmpty>()
	.Command<GetDataByEntityId>()
	.Command<InsertUsers>()
	.Command<UpdateRequest>()
	.Commit()
	.InvokeAsync();
```

**Comment by mrogunlana** [comment]
Or maybe something like: 

```
var result= await new TransactionHandler(ServiceLocator.Current)
	.Add(context.CancellationToken)
	.Add(new KeyValuePair("EntityId", Guid.Parse(request.EntityId)))
	.Validate<EntityIdNotNullOrEmpty>()
	.Command<GetDataByEntityId>()
	.Command<InsertUsers>()
	.Command<UpdateRequest>()
	.InvokeAsync();
```

Where the `TransactionHandler` would create the transaction and commit/rollback internally while passing the scope to the commands in the `Subject`.

This way handlers can be written normally and the configuration for committing or rolling back a transaction is done automagically

**Comment by mrogunlana** [comment]
CC: @oneEyedSunday `Panama.Core` v2.0.5 and `Panama.Core.MySql.Dapper` v2.0.6 now supports distributed database transactions across commands. 

see
1. https://github.com/mrogunlana/Panama.Core/blob/master/Panama.Core.Tests/MysqlTests.cs#L366 (success case: distributed transactions across commands including batch commands)
2. https://github.com/mrogunlana/Panama.Core/blob/master/Panama.Core.Tests/MysqlTests.cs#L393 (failure/rollback case: rolls back distributed transactions across commands including batch commands)

We should now be using `TransactionHandler` and write individual query commands normally without explicitly stating `START TRANSACTION`/`COMMIT` in the queries. This allows us to separate large query commands into more granular query commands which should allow for improved testability/readability of query commands

**Comment by mrogunlana** [comment]
For more information regarding how the `MySqlConnection` object handles ambient transactions, see: https://mysqlconnector.net/tutorials/migrating-from-connector-net/

Some people have reported that MySql.Data does not support "distributed transactions" (re: https://stackoverflow.com/questions/37390805/transactionscope-with-mysql-and-distributed-transactions) but from my tests above (re: https://github.com/mrogunlana/Panama.Core/issues/8#issuecomment-1017025079), we can at least distribute transactions via connections to the same database server within the context of a `Handler`. So, this tells me that the issue reported on the SO question may be an architectural issue since he is using the .NET IoC container to provide a `TransactionScope` for his web api endpoints whereas `Panama.Core` provides a `TransactionHandler`  which scopes transactions at a handler level. 

More testing in production environments will reveal how the new `TransactionHandler` handles connections to the same server across different databases within said server. It seems that the limitation to the `TransactionHandler` would be that it *may* not be able to handle connections to different database servers within the confines of a single `Handler`, but we shall see... a solution in these scenarios would be to use a different connector (re: https://mysqlconnector.net/overview/installing/) but time will tell us if this is necessary or not.  

A `MySql` database connection automatically enlists to an ambient transaction by default (re: https://dev.mysql.com/doc/dev/connector-net/6.10/html/P_MySql_Data_MySqlClient_MySqlConnection_ConnectionString.htm). So no additional configurations in production implementations are needed to support the distributed transactions provided by the `TransactionHandler`

**Comment by mrogunlana** [comment]
I stand corrected! 
Upon further tests across multiple databases (re: https://github.com/mrogunlana/Panama.Core/blob/master/Panama.Core.Tests/MysqlTests.cs#L423), I've reproduced the distributed transaction bug (re: https://stackoverflow.com/questions/37390805/transactionscope-with-mysql-and-distributed-transactions), I've moved the `Panama.Core.MySql.Dapper` library to use `MySqlConnector` and the distributed transaction test across multiple databases passed. As a result, the v2.0.8 of the `Panama.Core.MySql.Dapper` library has moved from `MySql.Data` client to `MySqlConnector` instead.

**Comment by oneEyedSunday** [comment]
I'm reading the links.

> https://github.com/mrogunlana/Panama.Core/issues/8#issuecomment-1016816728
For commands that span different dbs, this will be problematic

I see https://github.com/mrogunlana/Panama.Core/issues/8#issuecomment-1017415501 notes this concern
